//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gosocket.Dian.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gosocket.Dian.Common.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptación expresa.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alert.
        /// </summary>
        public static string alertType {
            get {
                return ResourceManager.GetString("alertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los archivos deben estar en estado &apos;Aceptado&apos; para poder cambiar el estado del participante..
        /// </summary>
        public static string AllSoftware {
            get {
                return ResourceManager.GetString("AllSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CaptchaError.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa no asociada a representante legal..
        /// </summary>
        public static string CompanyDoesntAssociate {
            get {
                return ResourceManager.GetString("CompanyDoesntAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a confirm.
        /// </summary>
        public static string confirmType {
            get {
                return ResourceManager.GetString("confirmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empresa no se encuentra habilitada..
        /// </summary>
        public static string DisabledCompany {
            get {
                return ResourceManager.GetString("DisabledCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder continuar, realiza el proceso de habilitación como Facturador Electrónico..
        /// </summary>
        public static string ElectronicBillerNoEnabled {
            get {
                return ResourceManager.GetString("ElectronicBillerNoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea habilitar  la trasmisión de eventos al RADIAN como Facturador Electrónico?.
        /// </summary>
        public static string ElectronicInvoice_Confirm {
            get {
                return ResourceManager.GetString("ElectronicInvoice_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico enviado correctamente.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Endoso electrónico.
        /// </summary>
        public static string Endoso {
            get {
                return ResourceManager.GetString("Endoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento equivalente &quot;{equivalentDocument}&quot; NO tiene set de pruebas configurado para el modo de operación {operationMode}. Comuníquese con el administrador del sistema..
        /// </summary>
        public static string EquivalentDocumentWithoutTestSet {
            get {
                return ResourceManager.GetString("EquivalentDocumentWithoutTestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factura Electrónica.
        /// </summary>
        public static string Event_DocumentType {
            get {
                return ResourceManager.GetString("Event_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mandato por documento.
        /// </summary>
        public static string Event_MandateType {
            get {
                return ResourceManager.GetString("Event_MandateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencias del evento.
        /// </summary>
        public static string Event_ReferenceTitle {
            get {
                return ResourceManager.GetString("Event_ReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Disponibilización para Negociaciación General.
        /// </summary>
        public static string Event_RequestType {
            get {
                return ResourceManager.GetString("Event_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificación.
        /// </summary>
        public static string Event_Status_01 {
            get {
                return ResourceManager.GetString("Event_Status_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento validado por la DIAN.
        /// </summary>
        public static string Event_ValidationMessage {
            get {
                return ResourceManager.GetString("Event_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validaciones del evento.
        /// </summary>
        public static string Event_ValidationTitle {
            get {
                return ResourceManager.GetString("Event_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El participante ya tiene asociado el software asignado!!!.
        /// </summary>
        public static string ExistingSoftware {
            get {
                return ResourceManager.GetString("ExistingSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea operar como Factor?.
        /// </summary>
        public static string Factor_Confirm {
            get {
                return ResourceManager.GetString("Factor_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se logro realizar la validación del participante a Registrar!!!.
        /// </summary>
        public static string FailedValidation {
            get {
                return ResourceManager.GetString("FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no se encuentra activo.
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta algún dato del formulario.
        /// </summary>
        public static string IncompleteForm {
            get {
                return ResourceManager.GetString("IncompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contribuyente tiene RUT en estado cancelado..
        /// </summary>
        public static string InvalidUserRut {
            get {
                return ResourceManager.GetString("InvalidUserRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña anterior no es correcta.
        /// </summary>
        public static string LastPasswordWrong {
            get {
                return ResourceManager.GetString("LastPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción de Mandato Electrónico.
        /// </summary>
        public static string Mandato {
            get {
                return ResourceManager.GetString("Mandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este modo de operación y documento electrónico carece de Set de Pruebas!!!.
        /// </summary>
        public static string ModeElectroniDocWithoutTestSet {
            get {
                return ResourceManager.GetString("ModeElectroniDocWithoutTestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ModelError.
        /// </summary>
        public static string ModelError {
            get {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este modo de operación carece de Set de Pruebas!!!.
        /// </summary>
        public static string ModeWithoutTestSet {
            get {
                return ResourceManager.GetString("ModeWithoutTestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no habilitado para el sistema!!!.
        /// </summary>
        public static string NonExistentParticipant {
            get {
                return ResourceManager.GetString("NonExistentParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene otro proceso activo con software propio..
        /// </summary>
        public static string OnlyActiveProcess {
            get {
                return ResourceManager.GetString("OnlyActiveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede registrar esta operación, tiene software en proceso!!..
        /// </summary>
        public static string OperationFailOtherInProcess {
            get {
                return ResourceManager.GetString("OperationFailOtherInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Esta operación no está permitida en el ambiente de producción!.
        /// </summary>
        public static string OperationNotAllowedInProduction {
            get {
                return ResourceManager.GetString("OperationNotAllowedInProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de operación adicionado correctamente.
        /// </summary>
        public static string OtherDocEleSuccesModeOperation {
            get {
                return ResourceManager.GetString("OtherDocEleSuccesModeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea iniciar el proceso de habilitación para @docume?.
        /// </summary>
        public static string OthersElectronicDocumentsSelect_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelect_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea habilitar la trasmisión de &quot;Otros Documentos Electrónicos&quot; en el sistema como @Participante de otros documentos electrónicos?.
        /// </summary>
        public static string OthersElectronicDocumentsSelectOperationMode_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelectOperationMode_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea iniciar el proceso como @Participante de otros documentos electrónicos?.
        /// </summary>
        public static string OthersElectronicDocumentsSelectParticipante_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelectParticipante_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos asociados correctamente..
        /// </summary>
        public static string OtherSuccessSoftware {
            get {
                return ResourceManager.GetString("OtherSuccessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El participante no cuenta con un software propio activo en el sistema.
        /// </summary>
        public static string ParticipantWithoutSoftware {
            get {
                return ResourceManager.GetString("ParticipantWithoutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe contener: al menos (1) mayúscula, (1) minúscula, (1) dígito, (1) símbolo o carácter especial y debe ser de almenos 6 carácteres..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PasswordError.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordsArentEquals {
            get {
                return ResourceManager.GetString("PasswordsArentEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada correctamente.
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://catalogo-vpfe.dian.gov.co/document/searchqr?documentkey={CUFE}.
        /// </summary>
        public static string RadianReportQRCode {
            get {
                return ResourceManager.GetString("RadianReportQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibo del bien y/o prestación del servicio.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acuse de recibo de Factura Electrónica de Venta.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a redirect.
        /// </summary>
        public static string redirectType {
            get {
                return ResourceManager.GetString("redirectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El participante ya se encuentra registrado en RADIAN.
        /// </summary>
        public static string RegisteredParticipant {
            get {
                return ResourceManager.GetString("RegisteredParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /document/searchqr?documentkey={CUFE}.
        /// </summary>
        public static string ReportQRCode {
            get {
                return ResourceManager.GetString("ReportQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El software es un campo obligatorio.
        /// </summary>
        public static string RequiredSoftware {
            get {
                return ResourceManager.GetString("RequiredSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible enviar el correo.
        /// </summary>
        public static string SendEmailFailed {
            get {
                return ResourceManager.GetString("SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor inicie sesión nuevamente e intente de nuevo.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Primera Disponibilización.
        /// </summary>
        public static string SolicitudDisponibilizacion {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Disponibilización Posterior.
        /// </summary>
        public static string SolicitudDisponibilizacion1 {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos actualizados correctamente..
        /// </summary>
        public static string SuccessSoftware {
            get {
                return ResourceManager.GetString("SuccessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El participante no es un proveedor tecnológico habilitado.
        /// </summary>
        public static string TechnologProviderDisabled {
            get {
                return ResourceManager.GetString("TechnologProviderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea habilitar la trasmisión de eventos al RADIAN como Proveedor Tecnológico?.
        /// </summary>
        public static string TechnologyProvider_Confirm {
            get {
                return ResourceManager.GetString("TechnologyProvider_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los participantes &apos;En pruebas&apos; no se pueden cancelar..
        /// </summary>
        public static string TestNotRemove {
            get {
                return ResourceManager.GetString("TestNotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea operar como Sistema de Negociación?.
        /// </summary>
        public static string TradingSystem_Confirm {
            get {
                return ResourceManager.GetString("TradingSystem_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue creado exitosamente.
        /// </summary>
        public static string UserCreatedSuccess {
            get {
                return ResourceManager.GetString("UserCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no existe o no está registrado.
        /// </summary>
        public static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UserError.
        /// </summary>
        public static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Usuario con el Tipo de Documento y Documento suministrados.
        /// </summary>
        public static string UserExistingDoc {
            get {
                return ResourceManager.GetString("UserExistingDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un Usuario con el correo suministrado.
        /// </summary>
        public static string UserExistingEmail {
            get {
                return ResourceManager.GetString("UserExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no puedo ser asignado al role &apos;Usuario Facturador Gratuito&apos;.
        /// </summary>
        public static string UserRoleFail {
            get {
                return ResourceManager.GetString("UserRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue actualizado exitosamente.
        /// </summary>
        public static string UserUpdatedSuccess {
            get {
                return ResourceManager.GetString("UserUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario no tiene una Empresa Asociada!.
        /// </summary>
        public static string UserWithOutCompany {
            get {
                return ResourceManager.GetString("UserWithOutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El software de la operación tiene {0} clientes asociados..
        /// </summary>
        public static string WithCustomerList {
            get {
                return ResourceManager.GetString("WithCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el captcha.
        /// </summary>
        public static string WrongCaptcha {
            get {
                return ResourceManager.GetString("WrongCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
