const bootboxMessage = {
    CONFIRMATION_MESSAGE: "¿Está seguro que quiere cancelar este usuario?",
    CHANGE_STATE: "¿Está seguro que desea cambiar el estado del archivo?",
    CANCEL_DESCRIPTION: "Describa el motivo de la cancelación del registro.",
    LABEL_PROMPT: "Describa el motivo de la cancelación del registro.",
    LABEL_STATUS: "Describa el motivo del cambio de estado.",
    CANCEL_REGISTER: "Cancelar registro",
    ACEPTAR: "Aceptar",
    CANCEL_RESPONSE_CORRECT: "Se canceló el registro exitosamente",
    CONFIRMATION_MESSAGE_DESACTIVE: "¿Desea inactivar el usuario seleccionado?",
    CONFIRMATION_MESSAGE_ACTIVE: "¿Desea activar el usuario seleccionado?",
    CONFIRMATION_CORRECT_ENABLED: "Estado actualizado correctamente",
    CONFIRMATION_RESTART: "¿Está seguro que desea reiniciar el set de pruebas?",
    CONFIRMATION_RESTART_COMPLEMENT: "Al realizar esta acción deberá enviar otro set de pruebas con documentos diferentes. Todas las estadísticas de la certificación serán reiniciadas",
};